### PR TITLE
Use objects for json encoding

### PR DESCRIPTION
**Pull request by prolic**
and move DateTimeUtil, Json and UuidGenerator to Util namespace 

/cc @fritz-gerneth @enumag

### CODE REVIEW

**Comment by enumag** [comment]
You might be interested in this UUID generator: https://gist.github.com/JanTvrdik/655b31e78e998bb468c7f8f8cfe4b3b6

**Comment by prolic** [comment]
wow, three times the speed, nice

**Comment by enumag** [comment]
Maybe you can get rid of the ramsey dependency with this?

**Comment by prolic** [comment]
Sure, if you can also send me the code to generate binary string from this :)
I use `\Ramsey\Uuid\Uuid::getBytes()` currently.

**Comment by prolic** [comment]
@enumag You can also send a PR if you find it.

**Comment by enumag** [comment]
I don't have such code sadly. I will try to look into it this weekend.

**Comment by prolic** [comment]
Probably we can steal something from ramsey lib, didn't check how it's
done. Just used it because it works.

**Comment by enumag** [comment]
> Probably we can steal something from ramsey lib, didn't check how it's done. Just used it because it works.

It won't be so easy. Ramsey has a different internal representation of the UUID, not simply a string.

**Comment by prolic** [comment]
Yes and uuid validation is also needed. Maybe not worth the effort. However
nice to have the simple generator in place.

**Pull request merged**
