### PR TITLE
remove sync implementations

### PR DESCRIPTION
**Pull request by prolic**
@pkruithof - note those changes
@enumag - sorry, but has to be done

Explanation:
Establishing a TCP connection is already some overhead to the application. For async environments that's no problem at all, because you do it only once on startup. But when using this in a traditional PHP application, you'll create tons of TCP connections, over and over again, thus slowing things down really much. I am also not sure if EventStore can really handle thousands of connections.
In PDO this is done in C, the connection is persistent across requests, but without having the EventStore connection handling written in C as an extension, it's not possible to do this efficiently.
Things get even worse when running things in a cluster.

The usual thing that happens is this:
- Send HTTP request to cluster to receive list of nodes
- Establish connection
- Authenticate
- The node may respond with "please connect to the other node X"

In a traditional blocking environment it's obviously the better choice to just use an HTTP client, hence the flow is this:

- Send HTTP request -> DONE

Even if you would send the request to the wrong node in the cluster, this would get routed to the correct node internally by the cluster.

If you still insist (against my advice) to use this library in a traditional, synchronous, blocking environment, you can use the `Amp\wait()` and `Amp\call()` functions to accomplish this:

```
wait(call(function () {
    $connection = ...;
    yield $connection->connectAsync();
    $slice = yield $connection->readStreamEventsForwardAsync( .... );
}));
```

Note:
I have already a prototype of an HTTP client ready in my pocket. This will get polished and then released soon after the client is released in final version.

### CODE REVIEW

**Comment by enumag** [comment]
I understand the reasons and while it will certainly complicate things for me I mostly agree.

I'm not exactly sure what I should do now though. How is your application written what does the eventstore usage look like in your case? Should I try to finish my wip migration of my application to swoole? How can I interconnect swoole and amp though?

**Comment by prolic** [comment]
See: https://github.com/swoole/library/blob/master/src/Swoole/Driver/Amp.php

I use Event Store in an Amp Event Loop. While swoole is nice to put it below ZF or Laravel, I dislike all the "magic tricks" it does (like patching other extensions).

Event Store HTTP Client will follow pretty soon (we are talking days / weeks and not months) with a pretty similar interface. So you can wait for that if you plan to use it in a traditional PHP application.

**Comment by enumag** [comment]
> I use Event Store in an Amp Event Loop. While swoole is nice to put it below ZF or Laravel, I dislike all the "magic tricks" it does (like patching other extensions).

I saw that a while ago when reading one of your issues in amp repo. But with my lack of knowledge about both amp and swoole I have absolutely zero idea how to use that thing.

> Event Store HTTP Client will follow pretty soon (we are talking days / weeks and not months) with a pretty similar interface. So you can wait for that if you plan to use it in a traditional PHP application.

Similar to what? The sync API I have been using until now? Sounds great.

Don't get me wrong, I'd love to get the application running on amp and/or swoole but I should probably rather approach this step by step. So I guess I'll stick to beta 7 of this repo for now, transition to the HTTP client when it's ready and try to do the better async stuff later on. That should work, right?

Transitioning into the async API will most likely require some more docs / examples from you about how to write such application with CQRS+ES etc. I feel it will be necessary to have such guide sooner or later since most of the PHP community doesn't have async experience just like myself. My guess is you're planning on doing that in a few months or so? Anyway it would be foolish for me to try it by myself.

Thank you very much for doing this. I'll try to help as I can with issues and bugfixes whenever I find anything as I have been until now.

**Comment by pkruithof** [comment]
We're running the async client inside a Symfony Flex application just fine. Only the event-store-client part is done with AMP, the rest just runs 'regularly'

**Comment by enumag** [comment]
@pkruithof I'd like to see some example how that works.

My application is not exactly a "standard" symfony flex application. It's a GraphQL API so I don't have controllers for example.

**Comment by enumag** [comment]
> But consuming from subscriptions happens in Symfony Console commands (we're building a faceless application too).

Yeah I'm trying to implement that right now since that should be rather easy. Still if you can share some pieces it would help me and you could get feedback and ideas from me.

How do you write data into the eventstore then? I mean you need to put some data in before you can consume them in subscribers.

> In any case, you can use the call and wait functions to avoid the loop stuff, I think.

Prolic clearly said it's not recommended with a good reasoning so I want to get rid of that sooner rather than later.

**Comment by pkruithof** [comment]
> Yeah I'm trying to implement that right now since that should be rather easy. Still if you can share some pieces it would help me and you could get feedback and ideas from me.

It's mostly like the code you see in the examples in this repo.

> How do you write data into the eventstore then? I mean you need to put some data in before you can consume them in subscribers.

We implemented an OuroEventStore implementation for the Prooph EventStore interface (the v7 one). That implementation uses the HTTP api to read/write events.

**Comment by enumag** [comment]
Ah, well then you're not doing anything too much different than what I'm planning, you're just quite a bit further down the road. :-)

**Comment by enumag** [comment]
I tried to implement the subscription based on [this example](https://github.com/prooph/event-store-client/blob/f4bc31fc4f1dcfa4593e672fbafc85a0ac27337c/examples/demo-persistent-subscription.php#L62-L93). The problem I'm facing now is that the event is not the real event I need but only contains the ID of the real event. I'm guessing this is because in the query I'm using `linkTo` instead of `emit` since that's what prolic used [here](https://github.com/prooph/event-store-client/issues/26#issuecomment-439297022) when we discussed it.

How should I solve this? Should I use `emit` after all or manually read the event from the eventstore when I receive the link? How can I retrieve the event using async connection? I mean I can't exatly call a method and yield inside of [this function](https://github.com/prooph/event-store-client/blob/f4bc31fc4f1dcfa4593e672fbafc85a0ac27337c/examples/demo-persistent-subscription.php#L71-L74) right?

**Comment by pkruithof** [comment]
You can get the original event from the resolved event that you're getting in the consumer. Our handler looks like this (simplified):

```php
final class EventAppearedHandler implements EventAppearedOnCatchupSubscription
{
    private $consumer;

    public function __invoke(Subscription $subscription, ResolvedEvent $resolvedEvent): Promise
    {
        $recordedEvent = $resolvedEvent->event();
        ($this->consumer)($recordedEvent);

        return new Success();
    }
}
```

**Comment by enumag** [comment]
I don't think you understand the problem... Maybe you're using a slightly different setup than I'm causing you to not have the problem?

Here is what I'm using:

1. Use the standard `$by_category` projection to create streams like `$ce-AggregateType1`, `$ce-AggregateType2`...
2. Use my own projection to aggregate all these into one stream:

```
fromStreams(
    '$ce-AggregateType1',
    '$ce-AggregateType2'
    // ...
).when({
    $any: function (s, e) {
        linkTo('everything', e);
    }
});

```

3. Create a persistent subscription on the `everything` stream.

Now when I receive a `ResolvedEvent` in the `EventAppearedOnCatchupSubscription` implementation the `ResolvedEvent` instance does not contain the real data, only an id of the event that happened. I tried both `$resolvedEvent->event()` and `$resolvedEvent->originalEvent()` but can't find the real data there. So I don't have the real event to send to the updater.

What are you doing differently? Or do you fetch the event in the consumer?

**Comment by pkruithof** [comment]
I see you're in https://gitter.im/prooph/improoph, let's continue there

**Comment by prolic** [comment]
Great you figured it out already. Sorry, I'm late to the party. As for Amp: this is a learning curve, definitely. Don't expect to be able to write async applications after reading a blog post. But some subscription is easy enough to do, you can do this, I'm sure.

**Comment by enumag** [comment]
> As for Amp: this is a learning curve, definitely. Don't expect to be able to write async applications after reading a blog post.

I most certainly don't. :-D But if you have tips on some good blog posts I should read then please tell me. ;-)

Subscription is working just fine now. I can start implement updaters tomorrow.

**Comment by prolic** [comment]
It's a little ugly, but this should help: https://github.com/prolic/awesomeness/blob/master/src/PostgresProjectionManager/bin/server.php

**Pull request merged**
