### PR TITLE
refactor event appeared callbacks

### PR DESCRIPTION
**Pull request by prolic**
@pkruithof note this change as well

### CODE REVIEW

**Comment by prolic** [comment]
Also resolves https://github.com/prooph/event-store-client/issues/44

**Comment by pkruithof** [comment]
As it seems, only internal stuff has changed, right? There were some points where we had to require internal classes, so I'll check those. But this mostly shouldn't affect anything, I think.

**Comment by prolic** [comment]
Mostly internal stuff, correct. But note your callbacks expect ResolvedEvent now and not Internal\ResolvedEvent.

**Comment by pkruithof** [comment]
Yeah, already updated those :-)

The only internal class I need to use right now is `Prooph\EventStoreClient\Internal\EventStorePersistentSubscription`

**Pull request merged**
