### PR TITLE
Allow ramsey/uuid v4.x

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by prolic** [comment]
@enumag Why not pin to 4.0 directly? I didn't check this new major release so far. What's the difference?

**Comment by prolic** [comment]
Looking at https://github.com/ramsey/uuid/releases/tag/4.0.0, I think pinning to 4.0 is the way to go. Thoughts?

**Comment by enumag** [comment]
I think that locking it at v4.0 might make sense when solving #119 since that might require using more of ramsey's features. But until then ramsey/uuid is just a minor dependency for us and the bc breaks don't affect us. Locking it at v4.0 needlessly would only cause unnecessary dependency conflicts for our users who might have dependencies on ramsey/uuid through some other libraries. It kinda depends on when you're planning on working on #119 but since you're busy lately I'm treating it as something that may or may not happen soon so I'm not including it into my considerations here.

**Comment by prolic** [comment]
I tried creating Guid's using 4.0 of this ramsey-lib and ended up creating an issue: https://github.com/ramsey/uuid/issues/306

**Comment by prolic** [comment]
solved via https://github.com/prooph/event-store/pull/387/

**Pull request closed without merging**
