### PR TITLE
cleanup deps

### PR DESCRIPTION
**Pull request by prolic**
resolves https://github.com/prooph/event-store-client/issues/72

### CODE REVIEW

**Comment by prolic** [comment]
@SunMar amphp/file 0.3.3 needs to stay as requirement. Actually it's required by amphp/artax already, but this one used 0.2 | 0.3 and 0.2 is not working as expected with this lib.

**Comment by prolic** [comment]
Same here: "amphp/byte-stream": "^1.5.0" - without that you cannot install via composer with "--prefer-lowest" option

**Comment by SunMar** [comment]
Ok, that's why I also asked about the other ones before :). A simple search for `use` statements doesn't always tell the whole story.

**Comment by prolic** [comment]
Yes, and I totally forgot what the reason behind this was.

**Pull request merged**
