### PR TITLE
remove unused dependencies from composer.json

### PR DESCRIPTION
**Pull request by SunMar**

### CODE REVIEW

**Comment by SunMar** [comment]
Hmm, @prolic I see the PHP 7.3 test failed, but I also see it was only recently added. Is it not ready yet and expected to fail, or has removing the dependencies introduced an issue I should look into?

**Comment by prolic** [comment]
All good, that's a known issue with the tests, see https://github.com/prooph/event-store-client/issues/67. It happens sporadically, no matter which PHP version you test. If you find the root cause, let me know. For me it's now not the most important part to work on, I'll focus on more serious issues for now. It's probably some timing issue.

**Comment by SunMar** [comment]
@prolic I can take a look if I can find something. Is there an easy way to run all the tests? I only work through Docker so I don't have any tooling installed locally. I do see a `docker/unittest` folder but I'm not sure what command I need to run to run the tests.

**Comment by SunMar** [comment]
@prolic uh nevermind, I found the `README.md` :)

**Comment by SunMar** [comment]
@prolic ok I can't seem to run the tests properly :(

I'm running:
```
docker-compose -f docker/unittest/docker-compose.yml run php /app/vendor/bin/phpunit -c phpunit/phpunit.xml --stop-on-failure
```

Which results in:

```
Starting unittest_eventstore_1 ... done
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

E

Time: 742 ms, Memory: 14.00MB

There was 1 error:

1) ProophTest\EventStoreClient\PersistentSubscriptionManagement\persistent_subscription_manager::can_describe_persistent_subscription
Error: Loop exceptionally stopped without resolving the promise

/app/vendor/amphp/amp/lib/functions.php:172
/app/tests/SpecificationWithConnection.php:54
/app/tests/PersistentSubscriptionManagement/persistent_subscription_manager.php:118

Caused by
PHPUnit\Framework\Error\Warning: include(/app/vendor/amphp/parallel/lib/Sync/ChannelledSocket.php): failed to open stream: No such file or directory

/app/vendor/amphp/parallel/lib/Context/Internal/ProcessHub.php:63
/app/vendor/amphp/amp/lib/Coroutine.php:41
/app/vendor/amphp/amp/lib/Loop/NativeDriver.php:213
/app/vendor/amphp/amp/lib/Loop/NativeDriver.php:97
/app/vendor/amphp/amp/lib/Loop/Driver.php:134
/app/vendor/amphp/amp/lib/Loop/Driver.php:72
/app/vendor/amphp/amp/lib/Loop.php:84
/app/vendor/amphp/amp/lib/functions.php:170
/app/tests/SpecificationWithConnection.php:54
/app/tests/PersistentSubscriptionManagement/persistent_subscription_manager.php:118

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

I'm kind of baffled by it, if I enter the container and do a `cat` the file `/app/vendor/amphp/parallel/lib/Sync/ChannelledSocket.php` is there and it's readable, no problem. Any idea?

**Comment by prolic** [comment]
Nope, that's new to me. Maybe I have time to investigate tomorrow.

**Comment by SunMar** [comment]
@prolic I was running it on a Windows machine, just now I tried it on my Mac and there it works fine so it's probably some annoying issue with Windows and Docker and bind mounts (it's not the first time I've had weird issues around files due to Windows and Docker not playing nice). So ignore it for now, if I need to run tests I'll do it on my Mac.

**Comment by prolic** [comment]
Good because I don't have windows :-)

**Pull request merged**
