### PR TITLE
renegerate client messages

### PR DESCRIPTION
**Pull request by prolic**
ping @enumag Can you try if that works better for you?

### CODE REVIEW

**Comment by prolic** [comment]
@enumag Can you check on gitter as well? I left you a message there.

**Comment by enumag** [comment]
@prolic Ah yeah, sorry gitter is not the best way to reach me since I'm rarely there. Twitter is far more reliable way to bother me haha. Anyway you have a reply on gitter now.

I'll test this out tomorrow morning when I get to work. I agree it's super weird that it only shows for me and not in tests. I already tried to update my protobuf extension and such but no change. Hopefully this will work. I'll let you know.

**Comment by enumag** [comment]
Yup, this branch works for me. :+1: Could you try to add back the `@var` annotations? It would be nice to have the types there at least in that way I think.

**Comment by enumag** [comment]
By the way, how do you generate these classes? I kinda expected for some generating script to be changed as well alongside this but that didn't happen.

**Comment by prolic** [comment]
Actually I don't want to add anything to those generated classes. I only run the php-cs-fixer and add the licence on top of that file, that's it.

How to generate?
Go to: `https://github.com/protocolbuffers/protobuf/releases`
Download and extract, for me this would be: `https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip`

There is the protocol buffers compiler. You can use it like this:
`/home/sasa/Downloads/protoc-3.11.4-linux-x86_64/bin/protoc --php_out src/Messages/ClientMessages ClientMessageDtos.proto`

The only thing is, it doesn't follow our psr-4 rules, so I have to move the generated files in the correct folder manually after that.

That's it.

**Pull request merged**
