### PR TITLE
PHP 8.1, amp v3

### PR DESCRIPTION
**Pull request by prolic**
- Require PHP 8.1
- make use of Fibers
- require amp v3

### CODE REVIEW

**Comment by dgafka** [comment]
I would be happy to integrate EventStoreDB to Ecotone Framework using Prooph's Event Store Client. 
However this currently is stuck on PHP 7.

@prolic @enumag @codeliner how can we push this forward? :)

**Comment by prolic** [comment]
There is a branch for PHP 8.1 support. Once amphp v3 is final, I'll release
the event store client in final as well.

**Comment by dgafka** [comment]
@prolic amazing waiting for it :)

**Comment by dgafka** [comment]
wow, that went quick: https://github.com/amphp/amp/releases/tag/v3.0.0

**Comment by prolic** [comment]
@dgafka as you can see in the latest commit https://github.com/prooph/event-store-client/pull/165/commits/7b9b55c6c72c2d691ec682035a4cbfe6552d4241, there are still some beta packages I use at the moment. Waiting for amphp team to release final version first.

**Comment by mbadolato** [comment]
@prolic Any update on this?

**Comment by mbadolato** [comment]
@prolic I have not tried it, no. Was waiting to hear if everything was updated and if @dgafka would be able to then add support to Ecotone

**Pull request merged**
